steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-model-train'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/mlops489-425700/mlops489-project/model-train:latest', '.', '-f', 'model-train.dockerfile']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-model-api'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/mlops489-425700/mlops489-project/model-api:latest', '.', '-f', 'model-api.dockerfile']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-model-train'
    waitFor: ['build-model-train']
    args: ['push', 'us-central1-docker.pkg.dev/mlops489-425700/mlops489-project/model-train:latest']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-model-api'
    waitFor: ['build-model-api']
    args: ['push', 'us-central1-docker.pkg.dev/mlops489-425700/mlops489-project/model-api:latest']


