wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716341742
    t:
      1:
      - 5
      - 6
      - 50
      - 53
      - 55
      2:
      - 5
      - 6
      - 50
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.11.5
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
config:
  desc: null
  value: '{''seed'': 17, ''n_estimators'': 100}'
