name: train model cml
on:
  pull_request:
    types: [opened, synchronize]
  workflow_run:
    workflows: ["dvc_pull.yaml"]
    types:
      - completed

jobs:
  run:
    if: ${{ github.even_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ubuntu-latest]
    env:
      RUN_CML: "true"
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install poetry
          poetry install
          poetry run python mlops_team_project/models/xgboost_model.py

      - name: Write Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} #might need to change
        run: |
          cat classification_report.txt >> report.md
          cml-publish confusion-matrix.png --md >> report.md
          cml-send-comment report.md
