name: mypy

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install MyPy
        run: pip install mypy
      - name: Run MyPy
        run: |
          find . -name "*.py" -exec mypy --ignore-missing-imports {} +
