name: MyPy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: MyPy
    steps:
      - uses: actions/checkout@v1
      - name: set python env
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
            pip install mypy
      - name: mypy
        run: |
          mypy src/
