name: ruff
on:  [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:    #Set up environment in container
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: 3.11
      - uses: chartboost/ruff-action@v1
        with:
         args: --check .
         fix_args: --fix .
         config: .ruff.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'code style -w ruff'

           

